### ISSUE TITLE
Error When build Implant

### ISSUE THREAD

**Issue by Epicccal** [DragoQCC/HardHatC2#13]
OS Version: 
```
> sw_vers 
ProductName:		macOS
ProductVersion:		13.2.1
BuildVersion:		22D68
```

Dotnet Version: 
```
> dotnet --version
7.0.305
```

Error msg 1:
```
Implant is an engineer
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.IO.DirectoryNotFoundException: Could not find a part of the path '/Users/test/weapons/HardHatC2-0.2-Alpha/DynamicEngLoading/bin/Debug'.
         at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
         at System.IO.Enumeration.FileSystemEnumerator`1.Init()
         at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
         at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
         at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
         at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
         at TeamServer.Utilities.Compile.GenerateEngCode(String source, EngCompileType compileType, SleepTypes sleepType, List`1 nonIncCommandList, List`1 nonIncModuleList) in /Users/test/weapons/HardHatC2-0.2-Alpha/TeamServer/Utilities/Compile.cs:line 43
         at TeamServer.Services.EngineerService.CreateEngineers(SpawnEngineerRequest request, String& result_message) in /Users/test/weapons/HardHatC2-0.2-Alpha/TeamServer/Services/IEngineerService.cs:line 193
         at TeamServer.Controllers.EngineersController.CreateEngineer(SpawnEngineerRequest request) in /Users/test/weapons/HardHatC2-0.2-Alpha/TeamServer/Controllers/EngineersController.cs:line 153
         at lambda_method166(Closure, Object, Object[])
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at TeamServer.Services.IPWhitelistService.Invoke(HttpContext context) in /Users/test/weapons/HardHatC2-0.2-Alpha/TeamServer/Services/IPWhitelistService.cs:line 35
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

Manually create directories

Error msg 2:
```
Implant is an engineer
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.IndexOutOfRangeException: Index was outside the bounds of the array.
         at TeamServer.Utilities.Compile.GenerateEngCode(String source, EngCompileType compileType, SleepTypes sleepType, List`1 nonIncCommandList, List`1 nonIncModuleList) in /Users/test/weapons/HardHatC2-0.2-Alpha/TeamServer/Utilities/Compile.cs:line 85
         at TeamServer.Services.EngineerService.CreateEngineers(SpawnEngineerRequest request, String& result_message) in /Users/test/weapons/HardHatC2-0.2-Alpha/TeamServer/Services/IEngineerService.cs:line 193
         at TeamServer.Controllers.EngineersController.CreateEngineer(SpawnEngineerRequest request) in /Users/test/weapons/HardHatC2-0.2-Alpha/TeamServer/Controllers/EngineersController.cs:line 153
         at lambda_method166(Closure, Object, Object[])
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at TeamServer.Services.IPWhitelistService.Invoke(HttpContext context) in /Users/test/weapons/HardHatC2-0.2-Alpha/TeamServer/Services/IPWhitelistService.cs:line 35
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

From the code, it seems that the `DynamicEngLoading.dll` is required
```
// get the shared library location 
string TopLevelFolder = pathSplit[0] + $"..{allPlatformPathSeperator}";
string DynamicLoadingDllPath = TopLevelFolder + "DynamicEngLoading" + allPlatformPathSeperator + "bin" + allPlatformPathSeperator + "Debug";
// in the TopLeelFolder should be files in the format Engineer_randomStrings.exe, we need one of those file paths 
string[] DynamicLoadingLibrary = Directory.GetFiles(DynamicLoadingDllPath, "DynamicEngLoading.dll");
... ... ... ...
// line 85 <- DynamicLoadingLibrary is null
Console.WriteLine("DynamicLoadingLibrary file path: " + DynamicLoadingLibrary[0]);
```

But I didn't find this file in the project path, how can i generate it？

Thank you！

**Comment by Epicccal** [comment]
> OS Version:
> 
> ```
> > sw_vers 
> ProductName:		macOS
> ProductVersion:		13.2.1
> BuildVersion:		22D68
> ```
> 
> Dotnet Version:
> 
> ```
> > dotnet --version
> 7.0.305
> ```
> 
> Error msg 1:
> 
> ```
> Implant is an engineer
> fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
>       An unhandled exception has occurred while executing the request.
>       System.IO.DirectoryNotFoundException: Could not find a part of the path '/Users/test/weapons/HardHatC2-0.2-Alpha/DynamicEngLoading/bin/Debug'.
>          at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
>          at System.IO.Enumeration.FileSystemEnumerator`1.Init()
>          at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
>          at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
>          at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
>          at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
>          at TeamServer.Utilities.Compile.GenerateEngCode(String source, EngCompileType compileType, SleepTypes sleepType, List`1 nonIncCommandList, List`1 nonIncModuleList) in /Users/test/weapons/HardHatC2-0.2-Alpha/TeamServer/Utilities/Compile.cs:line 43
>          at TeamServer.Services.EngineerService.CreateEngineers(SpawnEngineerRequest request, String& result_message) in /Users/test/weapons/HardHatC2-0.2-Alpha/TeamServer/Services/IEngineerService.cs:line 193
>          at TeamServer.Controllers.EngineersController.CreateEngineer(SpawnEngineerRequest request) in /Users/test/weapons/HardHatC2-0.2-Alpha/TeamServer/Controllers/EngineersController.cs:line 153
>          at lambda_method166(Closure, Object, Object[])
>          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
>          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
>          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
>       --- End of stack trace from previous location ---
>          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
>          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
>       --- End of stack trace from previous location ---
>          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
>          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
>          at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
>          at TeamServer.Services.IPWhitelistService.Invoke(HttpContext context) in /Users/test/weapons/HardHatC2-0.2-Alpha/TeamServer/Services/IPWhitelistService.cs:line 35
>          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>          at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
>          at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
>          at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
> ```
> 
> Manually create directories
> 
> Error msg 2:
> 
> ```
> Implant is an engineer
> fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
>       An unhandled exception has occurred while executing the request.
>       System.IndexOutOfRangeException: Index was outside the bounds of the array.
>          at TeamServer.Utilities.Compile.GenerateEngCode(String source, EngCompileType compileType, SleepTypes sleepType, List`1 nonIncCommandList, List`1 nonIncModuleList) in /Users/test/weapons/HardHatC2-0.2-Alpha/TeamServer/Utilities/Compile.cs:line 85
>          at TeamServer.Services.EngineerService.CreateEngineers(SpawnEngineerRequest request, String& result_message) in /Users/test/weapons/HardHatC2-0.2-Alpha/TeamServer/Services/IEngineerService.cs:line 193
>          at TeamServer.Controllers.EngineersController.CreateEngineer(SpawnEngineerRequest request) in /Users/test/weapons/HardHatC2-0.2-Alpha/TeamServer/Controllers/EngineersController.cs:line 153
>          at lambda_method166(Closure, Object, Object[])
>          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
>          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
>          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
>       --- End of stack trace from previous location ---
>          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
>          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
>       --- End of stack trace from previous location ---
>          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
>          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
>          at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
>          at TeamServer.Services.IPWhitelistService.Invoke(HttpContext context) in /Users/test/weapons/HardHatC2-0.2-Alpha/TeamServer/Services/IPWhitelistService.cs:line 35
>          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>          at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
>          at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
>          at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
> ```
> 
> From the code, it seems that the `DynamicEngLoading.dll` is required
> 
> ```
> // get the shared library location 
> string TopLevelFolder = pathSplit[0] + $"..{allPlatformPathSeperator}";
> string DynamicLoadingDllPath = TopLevelFolder + "DynamicEngLoading" + allPlatformPathSeperator + "bin" + allPlatformPathSeperator + "Debug";
> // in the TopLeelFolder should be files in the format Engineer_randomStrings.exe, we need one of those file paths 
> string[] DynamicLoadingLibrary = Directory.GetFiles(DynamicLoadingDllPath, "DynamicEngLoading.dll");
> ... ... ... ...
> // line 85 <- DynamicLoadingLibrary is null
> Console.WriteLine("DynamicLoadingLibrary file path: " + DynamicLoadingLibrary[0]);
> ```
> 
> But I didn't find this file in the project path, how can i generate it？
> 
> Thank you！

I know little about dotnet :(

So I open this project through Visual Studio 2022 IDE and try its "generate" function, then i get this `DynamicEngLoading.dll`
<img width="1409" alt="image" src="https://github.com/DragoQCC/HardHatC2/assets/34046030/d2efd74c-8f13-4225-b539-f901e28933e0">

final i can generate this implant
```
Implant is an engineer
DynamicLoadingLibrary file path: /Users/test/weapons/HardHatC2-0.2-Alpha/TeamServer/../DynamicEngLoading/bin/Debug/DynamicEngLoading.dll
INFO: IL Repack - Version 2.0.18
INFO: ------------- IL Repack Arguments -------------
/out:/Users/test/weapons/HardHatC2-0.2-Alpha/TeamServer/../Engineer_http_test.exe  /Users/test/weapons/HardHatC2-0.2-Alpha/TeamServer/temp/Engineer_http_test.exe /Users/test/weapons/HardHatC2-0.2-Alpha/TeamServer/Data/fastJSON.dll /Users/test/weapons/HardHatC2-0.2-Alpha/TeamServer/../DynamicEngLoading/bin/Debug/DynamicEngLoading.dll
-----------------------------------------------
INFO: Adding assembly for merge: /Users/test/weapons/HardHatC2-0.2-Alpha/TeamServer/temp/Engineer_http_test.exe
INFO: Adding assembly for merge: /Users/test/weapons/HardHatC2-0.2-Alpha/TeamServer/Data/fastJSON.dll
INFO: Adding assembly for merge: /Users/test/weapons/HardHatC2-0.2-Alpha/TeamServer/../DynamicEngLoading/bin/Debug/DynamicEngLoading.dll
INFO: Processing references
INFO: Processing types
INFO: Merging <Module>
INFO: Merging <Module>
INFO: Merging <Module>
INFO: Renaming Microsoft.CodeAnalysis.EmbeddedAttribute into <32568e27-2b1b-4cec-b1cc-83ca02c0bea7>EmbeddedAttribute
INFO: Renaming System.Runtime.CompilerServices.RefSafetyRulesAttribute into <cf9bb814-a176-4da4-8c6d-e1184d579264>RefSafetyRulesAttribute
INFO: Renaming <PrivateImplementationDetails> into <af325305-62b8-4da6-b585-719430d19196><PrivateImplementationDetails>
INFO: Processing exported types
INFO: Processing resources
INFO: Fixing references
WARN: Did not write source server data to output assembly. Source server data is only writeable on Windows
INFO: Writing output assembly to disk
INFO: Finished in 00:00:00.5719200
Merged Engineer and needed dlls
```

How to generate this dll only by `dotnet` command？Perhaps the docs should be updated :）

Thank you very much !!!

**Comment by DragoQCC** [comment]
Hey, I had forgotten that GitHub would ignore those files. I moved a copy of the required dll into the data folder on the teamserver that all the builds use. Please check if the lastest update fixed this fro you.

**Comment by DragoQCC** [comment]
Since I have updated the code to resolve this, and it has been tested to be resolved, I'm going to close this issue. If you perform a git pull/ clone of the latest update and still have the issue, please reopen it.
