### ISSUE TITLE
Error generating exe

### ISSUE THREAD

**Issue by nickswink** [DragoQCC/HardHatC2#2]
I am getting this error on the Client console when trying to generate an engineer for an HTTP listener. Looks to be some internal compilation error. 
I am on OSX montery and Teamserver is on Debian.

```
JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfte
rRenderAsync lifecycle method.                                                                                                                                                                 
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)                   
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)                                                
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](String identifier, CancellationToken cancellationToken, Object[] args)                                                                            
   at Blazored.LocalStorage.BrowserStorageProvider.GetItemAsync(String key, CancellationToken cancellationToken)                                                               
   at Blazored.LocalStorage.LocalStorageService.GetItemAsync[T](String key, CancellationToken cancellationToken)                                                                                                 
   at HardHatC2Client.Services.MyAuthenticationStateProviderService.GetAuthenticationStateAsync() in /Users/Username/Documents/Hardhat/HardHatC2-0.1-Alpha/HardHatC2Client/Services/MyAuthenticationStateProviderServi
ce.cs:line 25                                                                                                                                                               
"Merging of exe and needed dlls failed, check teamServer Console for errors."                                                                                                                  
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]                                                                                     
      Unhandled exception rendering component: Request failed with status code BadRequest                                                                       
      System.Net.Http.HttpRequestException: Request failed with status code BadRequest                                                                               
         at RestSharp.ResponseThrowExtension.ThrowIfError[T](RestResponse`1 response)                                                                                
         at RestSharp.RestClientExtensions.PostAsync[T](IRestClient client, RestRequest request, CancellationToken cancellationToken)                                   
         at HardHatC2Client.Pages.Engineers.CreateEngineer() in /Users/Username/Documents/Hardhat/HardHatC2-0.1-Alpha/HardHatC2Client/Pages/Engineers.razor:line 511            
         at HardHatC2Client.Pages.Engineers.validSubmit() in /Users/Username/Documents/Hardhat/HardHatC2-0.1-Alpha/HardHatC2Client/Pages/Engineers.razor:line 328                      
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)                                                         
         at MudBlazor.MudBaseButton.OnClickHandler(MouseEventArgs ev)                                                                                                
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)                                                               
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)                                 
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]                                                                                                         
      Unhandled exception in circuit '8yOfeELMdGAc-jSGkOwi4SM9_5QFP5t_**********'.                                                                                                
      System.Net.Http.HttpRequestException: Request failed with status code BadRequest                                                                                                 
         at RestSharp.ResponseThrowExtension.ThrowIfError[T](RestResponse`1 response)                                                                                                      
         at RestSharp.RestClientExtensions.PostAsync[T](IRestClient client, RestRequest request, CancellationToken cancellationToken)                                                  
         at HardHatC2Client.Pages.Engineers.CreateEngineer() in /Users/Username/Documents/Hardhat/HardHatC2-0.1-Alpha/HardHatC2Client/Pages/Engineers.razor:line 511                               
         at HardHatC2Client.Pages.Engineers.validSubmit() in /Users/Username/Documents/Hardhat/HardHatC2-0.1-Alpha/HardHatC2Client/Pages/Engineers.razor:line 328           
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)                                                                                             
         at MudBlazor.MudBaseButton.OnClickHandler(MouseEventArgs ev)                                                                                                                                     
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)                                                                                             
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)                                                                      
JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfte
rRenderAsync lifecycle method.                                                                                                                                                                 
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)       
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)                                                
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](String identifier, CancellationToken cancellationToken, Object[] args)                                                                            
   at Blazored.LocalStorage.BrowserStorageProvider.GetItemAsync(String key, CancellationToken cancellationToken)                                                                                               
   at Blazored.LocalStorage.LocalStorageService.GetItemAsync[T](String key, CancellationToken cancellationToken)                                                                                                 
   at HardHatC2Client.Services.MyAuthenticationStateProviderService.GetAuthenticationStateAsync() in /Users/Username/Documents/Hardhat/HardHatC2-0.1-Alpha/HardHatC2Client/Services/MyAuthenticationStateProviderServi
ce.cs:line 25
```

**Comment by DragoQCC** [comment]
Hey, I think I just fixed this bug with the newest commit it was checking for a DLL name that was cased correctly. Could you see if the TeamServer output has a specific error this client side is just a generic hey there is a problem message.

**Comment by nickswink** [comment]
Yeah here is the Team server output 

```
INFO: IL Repack - Version 2.0.18
INFO: ------------- IL Repack Arguments -------------
/out:/root/hardhat/HardHatC2-0.1-Alpha/TeamServer/../Engineer_asdfasdf.exe  /root/hardhat/HardHatC2-0.1-Alpha/TeamServer/temp/Engineer_asdfasdf.exe /root/hardhat/HardHatC2-0.1-Alpha/TeamServer/Data/FastJSON.dll
-----------------------------------------------
INFO: Adding assembly for merge: /root/hardhat/HardHatC2-0.1-Alpha/TeamServer/temp/Engineer_asdfasdf.exe
INFO: Adding assembly for merge: /root/hardhat/HardHatC2-0.1-Alpha/TeamServer/Data/FastJSON.dll
ERROR: Failed to load assembly /root/hardhat/HardHatC2-0.1-Alpha/TeamServer/Data/FastJSON.dll
Could not find file '/root/hardhat/HardHatC2-0.1-Alpha/TeamServer/Data/FastJSON.dll'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.GetFileStream(String fileName, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Mono.Cecil.AssemblyDefinition.ReadAssembly(String fileName, ReaderParameters parameters)
   at ILRepacking.ILRepack.ReadInputAssembly(String assembly, Boolean isPrimary)
   at ILRepacking.ILRepack.ReadInputAssemblies()
   at ILRepacking.ILRepack.Repack()
   at TeamServer.Utilities.MergeAssembly.MergeAssemblies(String outfileName, String[] sources, String searchdir) in /root/hardhat/HardHatC2-0.1-Alpha/TeamServer/Utilities/MergeAssembly.cs:line 24
Merged Engineer and needed dlls
Could not find file '/root/hardhat/HardHatC2-0.1-Alpha/Engineer_asdfasdf.exe'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.ReadAllBytes(String path)
   at TeamServer.Controllers.EngineersController.CreateEngineer(SpawnEngineerRequest request) in /root/hardhat/HardHatC2-0.1-Alpha/TeamServer/Controllers/EngineersController.cs:line 310

```

**Comment by DragoQCC** [comment]
hey, yep that is the same bug i just fixed during my testing, please download the latest version, and it should work fine, otherwise, you can edit the line here `TeamServer/Controllers/EngineersController line 302` change FastJSON to fastJSON, lowercase f.

**Comment by nickswink** [comment]
just pulled the latest and works, thanks

**Comment by DragoQCC** [comment]
yep its linked in the bottom of the readme https://discord.gg/npW2yy7JFK
